[skt_id]
  type = "String"


[ruleset_name]
  type = "String"


[recociliation_date]
  type = "Date"




[status]
  type = "String"


[comment]
  type = "String"


[tag]
  type = "String"



[a_skt_d]
  type = "String"


[a_skt_created]
  type = "Date"



[a_stt]
  type = "Number"


[a_ms_date]
  type = "Date"








[a_mstransid]
  type="String"


[a_ms_receipt_id]
  type = "String"


[a_ms_tx_status]
  type = "Boolean"


[a_mstotal_amount]
  type="Number"


[a_file_id]
  type = "String"


[a_filename]
  type = "String"


[a_skt_uniqueness]
  type = "Number"










[b_skt_id]
  type = "String"


[b_skt_created]
  type = "Date"


[b_skt_created_date]
  type = "Date"


[b_id]
  type = "Number"


[b_created_at]
  type = "Date"


