[skt_id]
  type = "String"

[ruleset_name]
  type = "String"

[recociliation_date]
  type = "Date"

[status]
  type = "String"

[comment]
  type = "String"

[tag]
  type = "String"

[a.skt_id]
  type = "String"

[a.skt_created_at]
  type = "Date"

[a.skt_created_date]
  type="Date"

[a.stt]
  type = "Number"

[a.ms_date]
  type = "Date"

[a.mstransid]
  type="String"

[a.ms_receipt_id]
  type = "String"

[a.ms_tx_status]
  type = "Boolean"

[a.mstotal_amount]
  type="Number"

[a.file_id]
  type = "String"

[a.filename]
  type = "String"

[a.skt_uniqueness]
  type = "Number"

[b.skt_id]
  type = "String"

[b.skt_created_at]
  type = "Date"

[b.skt_created_date]
  type = "Date"

[b.id]
  type = "Number"

[b.created_at]
  type = "Date"

[b.amount]
  type = "Number"

[b.order_ref]
  type = "String"

[b.merchant_order_ref]
  type = "String"

[b.channel_order_ref]
  type = "String"


[b.status_reason]
  type = "Boolean"

[b.file_id]
  type = "Number"

[b.filename]
  type = "String"

[b.skt_uniqueness]
  type = "Number"


